name: CI

on:
  push:
    branches: [main]
    tags:
      - '*@*'
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: write
  id-token: write
  pages: write
  actions: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && secrets.RELEASE_TOKEN || github.token }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.7.4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: deno-${{ hashFiles('deno.lock') }}
          restore-keys: deno-
      - uses: actions/setup-node@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Clear auth token for OIDC
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV
      - name: Update npm
        if: startsWith(github.ref, 'refs/tags/')
        run: npm install -g npm@latest
      - name: Run CI
        run: deno run --allow-env --allow-net --allow-sys --allow-run --allow-read --allow-write scripts/ci.ts
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
